#!/bin/sh

# list all paths under the current working directory that contain all (default) of the given search strings.
# excludes the directories node_modules/.git/cache/vendor.
# arguments: [lines-filter-options ...] search-string ...
# examples:
#   fig test

find_files() {
  find . -type d \( -name node_modules -o -name .git -o -name cache -o -name vendor \) -prune -o -type f -print
}

for a in "$@"; do pattern="${pattern} \"$a\""; done

find_files | ugrep --color=never -iUI -% "$pattern"
