#!/bin/sh

# :: path/find-arguments
# find files under directory ordered by descending modification time.
# all find arguments that can come before -printf are supported.
# depends on shell, find, sort and cut

find $@ -printf '%T@ %P\n' | sort --reverse --numeric-sort | cut --characters=23-
