#!/usr/bin/guile
!#
(import (sph filesystem) (sph hashtable) (sph io) (sph list) (sph number) (sph other) (sph process) (sph string) (sph vector) (sph))

(display (apply make-path-unique (tail (program-arguments))))