#!/usr/bin/guile
!#

(import (sph filesystem) (sph hashtable) (sph io) (sph list) (sph number) (sph other) (sph process) (sph string) (sph vector) (sph) (sph cli))

(define command-line-interface
  (cli-create #:options (list-q ((path-directory path-file ...) #:value-required? #t #:required? #t))
    #:description "ensures that a directory exists and moves all specified files into it"))

(define (move-into-directory path-directory path-file) (ensure-directory-structure path-directory)
  (let (path-file (delete path-directory path-file))
    (if (null? path-file) #t
      (apply execute "mv" (cli-option "target-directory" path-directory) path-file))))

(let (arguments (command-line-interface))
  (if (null? arguments) (command-line-interface (list "--help"))
    (move-into-directory (alist-ref-q arguments path-directory) (alist-ref-q arguments path-file))))
