#!/usr/bin/guile
!#

(import (sph base) (sph cli) (sph two) (rnrs io ports))

(define command-line-interface
  (cli-create #:options
    (list-q ((target-directory source-path ...) #:required? #t) (keep-directory-structure? #:names #\k))
    #:description "move files and replace the source paths with symlinks to the move destination"))

(define (move-and-link-cli)
  (let*
    ((cli-options (command-line-interface)) (source-paths (alist-ref cli-options (q source-path))))
    (if source-paths
      (let (target-directory (alist-ref cli-options (q target-directory)))
        (map
          (if (alist-q-ref cli-options keey-directory-structure?)
            (l (e) (move-and-link (path-append target-directory (dirname e)) e))
            (l (e) (move-and-link target-directory e)))
          source-paths))
      (command-line-interface (list "--help")))))

(move-and-link-cli)
