#!/usr/bin/guile
!#

; search :: search-string ...
; search inside files under the current working directory and list paths of matching files

(import (sph) (sph process) (sph process create))

(define (searchl-cli to-search . to-filter) (execute "clear")
  (process-chain-finish-success?
    (process-chain #f (current-output-port)
      (list
        (list "grep" "--files-with-matches"
          "--dereference-recursive" "--ignore-case" "--fixed-strings" to-search)
        (pair "lines-filter" to-filter))
      #:search-path? #t)))

(apply searchl-cli (tail (program-arguments)))
