#!/usr/bin/guile
!#

; searchl :: search-string ...
; search for strings inside files under the current working directory and list matching lines
(import (sph) (sph process) (sph process create))

(define (searchl-cli to-search . to-filter) (execute "clear")
  (process-chain-finish-success?
    (process-chain #f (current-output-port)
      (list
        (list "grep" "--dereference-recursive"
          "--fixed-strings" "--ignore-case" "--line-number" to-search)
        (pair "lines-filter" to-filter))
      #:search-path? #t)))

(apply searchl-cli (tail (program-arguments)))
