#!/usr/bin/guile
!#

; search :: search-string ...
; search for strings inside files under the current working directory and list paths of matching files
(use-modules (srfi srfi-1) (sph) (sph process) (sph process create))

(define (search-cli to-search . to-filter) (execute "clear")
  (let*
    ( (lines
        (process-chain->string #f
          (list
            (list "grep" "--dereference-recursive"
              "--exclude-dir=node_modules" "--exclude-dir=vendor"
              "--fixed-strings" "--ignore-case" "--line-number" "--binary-files=without-match" to-search)
            (pair "lines-filter" to-filter))
          #:search-path? #t))
      (file-paths
        (remove string-null?
          (map (l (a) (first (string-split a #\:))) (string-split lines #\newline)))))
    (each display-line (delete-duplicates file-paths))))

(apply search-cli (tail (program-arguments)))
