#!/bin/sh
# searchl :: search-string ...
# search for string inside files under the current working directory and list matching lines
clear
grep --dereference-recursive --ignore-case --line-number --fixed-strings "$@" *
