#!/usr/bin/guile
!#

(import (sph filesystem) (sph hashtable) (sph io) (sph list) (sph number) (sph other) (sph process) (sph string) (sph vector) (sph) (ice-9 rdelim) (guile))

(rw-port->port (l (port) (read-delimited " " port (q concat)))
  (l (a port) (display (string-downcase-first a) port)) (current-input-port) (current-output-port))