#!/usr/bin/guile
!#

(import (sph process) (sph))
(define width (string-trim-right (shell-eval->string "zenity --entry")))
(if (string->number width) (apply execute "scale-images" width (tail (program-arguments))))
