#!/bin/sh
# takes a screenshot every n seconds
# depends on "scrot"

# config
interval=24
destination=$HOME/temp/other/repeated-screenhots/$(d)

mkdir -p $destination
while true; do
  scrot --focused $destination/%s.png
  sleep $interval
done
