#!/usr/bin/env guile
!#

(import (sph base) (sph cli))

(define (scale-image width path-source path-dest)
  (execute "gm" "convert"
    "-size" (string-append width ">x")
    path-source "-resize" (string-append width ">x") "+profile" "*" path-dest))

(define (scale-images-cli)
  (let*
    ( (d "scaled")
      (cli
        (cli-create #:options (list-q ((width path ...)))
          #:description
          (string-append "scales images given by paths using graphicsmagick. a new directory "
            (string-quote d) " is created in the current directory where result images are put")))
      (arguments (cli)))
    (alist-bind arguments (width path)
      (if (and width path)
        (begin (ensure-directory-structure d)
          (each (l (a) (scale-image width a (string-append d "/" (basename a)))) path))
        (cli (list "--help"))))))

(scale-images-cli)
