#!/usr/bin/env ruby

def display_ratio_values ratio
  if ARGV.empty?
    puts "missing 1 number argument"
    return
  end
  s = ARGV[0].to_f
  i = [s * ratio]
  d = [s / ratio]
  10.times{i.unshift(i.first * ratio); d.unshift(d.first / ratio)}
  i.each{|a| puts "#{format("%.3f",a)} #{a}"}
  puts
  d.reverse.each{|a| puts "#{format("%.3f",a)} #{a}"}
end

display_ratio_values 2.414213562373095
