#!/bin/sh
# automatically chooses and creates the target directory.
# _ :: scrot-arguments
# dependencies: scrot

destination=$HOME/temp/screenshots/
mkdir -p $destination && scrot $destination/%s.png "$@"
