#!/bin/sh
# takes a screenshot every n seconds
# dependencies: scrot

# config
interval=24
destination=$HOME/temp/other/repeated-screenhots/$(iso-date)

mkdir -p $destination
while true; do
  scrot --focused $destination/%s.png
  sleep $interval
done
