#!/bin/sh
# take a screenshot of the currently focused window and store it in the directory configured in "take-screenshot", with the filename being the posixtime at creation
take-screenshot --focused
