#!/bin/sh
# takes a screenshot every n seconds
# dependencies: scrot

# config
interval=200
destination_root="$HOME/temp/other/interval-screenhots"

echo destination: $destination_root, interval: $interval "s"

date=$(date +%Y-%m-%d.%j)

while true; do
  destination="$destination_root/$date"
  mkdir -p $destination
  scrot --focused --quality 50 "$destination/$(day-seconds).jpg"
  sleep $interval
done
