#!/bin/sh
# automatically chooses and creates the target directory.
# _ :: scrot-arguments
# dependencies: scrot

destination=$HOME/nosync/screenshots/
mkdir -p $destination && scrot "$destination/%Y-%m-%d_%H:%M.png" "$@"
