#!/usr/bin/guile
!#

(import (rnrs sorting) (sph common) (sph cli))

(define (path-add-names path names)
  (string-append (dirname path) "/"
    (string-join
      (delete-duplicates-sorted
        (list-sort string< (append (string-split (basename path) #\.) names)))
      ".")))

(define (name-add names paths)
  (debug-log names paths)
  #;(let (names (filter (l (ele) (not (string-null? ele))) names))
    (if (not (null? names))
      (each
        (l (path)
          (let* ((path (path->full-path path)) (next-path (path-add-names path names)))
            (if (not (string=? next-path path))
              (rename-file path (get-unique-target-path next-path)))))
        paths))))

(define (name-add-cli)
  (apply name-add
    (alist-select ((cli-create #:options (ql ((names path ...) #:required? #t)))) (ql names path))))
