#!/usr/bin/guile
!#

(import (rnrs sorting) (sph list)
  (only (sph filesystem) get-unique-target-path path->full-path) (sph)
  (sph string) (sph cli-old) (only (sph time) seconds->iso-date-string))

(define config.exec (cli-init))
(define keyless-args (assoc-ref config.exec (q ())))

(define (path-replace-names path names)
  (string-append (dirname path) "/"
    (string-join (delete-duplicates-sorted (list-sort string< names)) ".")))

(define (filter-not-string-null arg) (filter (l (ele) (not (string-null? ele))) arg))

(define (name-del names paths)
  (let (names (filter-not-string-null names))
    (if (not (null? names))
      (each
        (l (path)
          (let*
            ( (path (path->full-path path))
              (new-names (complement (string-split (basename path) #\.) names)))
            (if (not (null? new-names))
              (let (next-path (path-replace-names path new-names))
                (if (not (string=? next-path path))
                  (rename-file path (get-unique-target-path next-path)))))))
        paths))))

(name-del (string-split (first keyless-args) #\.) (tail keyless-args))