#!/usr/bin/guile
!#

(import (sph process) (sph) (sph filesystem))

(define (move name . paths)
  (if (> (string-length name) 0)
    (begin (if (not (file-exists? name)) (mkdir name))
      (if (is-directory? name) (apply execute "mv" "-t" name paths)
        (debug-log "target exists and is not a directory")))))

(apply move (tail (program-arguments)))