#!/bin/sh

# copy all tracks from an audio disc as separate files to the current, or a specified, directory and eject the disc.

if test -n "$1" -a "$PWD" != "$1"
then
  mkdir -p "$1"
  cd "$1"
fi

cdparanoia -B && eject
