#!/usr/bin/guile
!#

(import (sph filesystem) (sph hashtable) (sph io) (sph list) (sph number) (sph other) (sph process) (sph string) (sph vector) (sph) (sph media-info))

(each (l (a) (display-line (string-append (first a) ": " (any->string (tail a)))))
  (media-info-video (first (tail (program-arguments)))))
