#!/usr/bin/guile
!#

(import (sph common) (sph media-info))

(each (l (a) (display-line (string-append (first a) ": " (any->string (tail a)))))
  (media-info-video (first (tail (program-arguments)))))
