#!/usr/bin/env guile
!#

(import (sph filesystem) (sph hashtable) (sph io) (sph list) (sph number) (sph other) (sph process) (sph string) (sph vector) (sph) (sph media-info))

(define (media-video-resolution paths)
  (map
    (l (path)
      (let (data (media-info-video path))
        (if data
          (display-line
            (string-append (number->string (alist-ref data "width")) "x"
              (number->string (alist-ref data "height")))))))
    paths))

(media-video-resolution (tail (program-arguments)))
