#!/usr/bin/env node

"use strict"
const fs = require("fs")
const path = require("path")
const input_paths = process.argv.slice(2)
if (input_paths.length === 0) process.exit(0)
input_paths.forEach(input_path => {
  let file_stat
  try {
    file_stat = fs.statSync(input_path)
  } catch (e) {
    return
  }
  if (!file_stat.isFile()) return
  const directory_name = path.dirname(input_path)
  const file_name = path.basename(input_path)
  const match = file_name.match(/^q\d+d\d+\.(.+)$/)
  if (!match) return
  const new_file_name = match[1]
  const new_file_path = path.join(directory_name, new_file_name)
  if (new_file_path === input_path) return
  fs.renameSync(input_path, new_file_path)
})
