#!/bin/sh
# split-flac-cue :: path-file-cue path-file-flac
# split a flac file corresponding to a cue file
# depends on "shnsplit" from "shntool"

file=$1
cue=$2
shnsplit -f "$cue" -o flac -t "%n.%t" "$file" < "$cue"
