#!/usr/bin/guile
!#

(import (sph filesystem) (sph hashtable) (sph io) (sph list) (sph number) (sph other) (sph process) (sph string) (sph vector) (sph) (sph cli))

(let
  (arguments
    ( (cli-create #:options
        (list-q ((input output) #:required? #t) (astyle-options #:value-required? #t) (dry-run)))))
  (alist-bind arguments (output input astyle-options dry-run)
    ( (if dry-run display-line shell-eval)
      (string-append "astyle --style=gnu --indent=spaces=2 "
        (if astyle-options (string-append astyle-options " ") "") " < "
        (string-quote input) " > " (string-quote output)))))
