#!/bin/dash
js-beautify --indent-with-tabs --jslint-happy
#uglifyjs --beautify "semicolons=false,indent-level=2,quote_style=2,width=120" --comments all $* | javascript-format-fixes | unexpand --tabs=2 --first-only
