#!/bin/dash
uglifyjs --beautify "semicolons=false,indent-level=2,quote_style=2,width=120" --comments all $* | remove-double-newlines | javascript-format-add-function-spacing | javascript-remove-semicolons | unexpand --tabs=2 --first-only
