#!/usr/bin/guile
!#

(import (sph filesystem) (sph hashtable) (sph io) (sph list) (sph number) (sph other) (sph process) (sph string) (sph vector) (sph) (sph cli))

(let
  (arguments
    ( (cli-create #:options
        (list-q ((output input) #:required? #t) (json-options #:value-required? #t) (dry-run)))))
  (alist-bind arguments (output input json-options dry-run)
    ( (if dry-run display-line shell-eval)
      (string-append "json " (if json-options (string-append json-options " ") "")
        "-f " (string-quote input) " > " (string-quote output)))))
