#!/usr/bin/guile
!#

(import (sph base) (sph filesystem tag) (sph alist) (sph cli))

(define (tag-add-cli)
  (let (arguments ((cli-create #:options (list-q ((tags path ...) #:required? #t)))))
    (alist-bind arguments (tags path) (tag-add (string-split tags #\.) path))))

(tag-add-cli)
