#!/usr/bin/guile
!#

(use-modules (sph alist) (sph other) (sph) (sph cli) (sph time string) (ice-9 regex))
(define regexp-hms (make-regexp "([01]?[0-9]|2[0-3]):([0-5]?[0-9])(:[0-5]?[0-9])?"))

(define (hms-to-minutes-cli)
  (let (arguments ((cli-create #:options (q (((hms)))))))
    (display-line (/ (seconds-from-hms (alist-ref-q arguments hms)) 60))))

(hms-to-minutes-cli)
