#!/bin/sh

# like create-filelist but also adds the xxhash of every file

if test -z $1
then
  echo missing argument
  exit
fi

a="/home/nonroot/t/file-list/$1-with-checksums"

# disk size/usage header
df --si --output=size,avail,pcent . > "$a"

# file listing
find . -xdev -type f | xargs -d \\n xxhsum >> "$a"

echo "written to $a"
