#!/usr/bin/guile
!#

;displays the sum of the number of bits of content of files, from a call to stat. input is a newline separated list of files read from standard input.
;the number of bits is supposed to be for the actual content and not the space usage in the file system, for example it is not rounded to the block size
(import (sph) (sph stream) (srfi srfi-41))

(display
  (stream-fold (l (r e) (catch #t (l () (+ (* 8 (stat:size (stat e))) r)) (l exc r))) 0
    (port->line-stream (current-input-port))))

(newline)
