#!/usr/bin/env guile
!#

(import (sph common) (sph media-info))

(let (paths (map path->full-path (tail (program-arguments))))
  (each
    (l (a)
      (let
        (new-name
          (regexp-replace (regexp-replace (basename a) "(br|fr|kbr|res|pxs|q)[x0-9]+\\." "")
            "q[0-9a-z]+-[0-9a-z]+-[0-9a-z]+\\." ""))
        (rename-file a (string-append (dirname a) "/" new-name))))
    paths))
