#!/usr/bin/guile
!#

(import (sph filesystem) (sph hashtable)
  (sph io) (sph list) (sph alist)
  (sph number) (sph other)
  (sph process) (sph string) (sph vector) (sph) (sph filesystem tag) (sph cli))

(define (tag-remove-cli)
  (let (arguments ((cli-create #:options (q (((tags path ...) #:required? #t))))))
    (alist-bind arguments (tags path) (tag-remove (string-split tags #\.) path))))

(tag-remove-cli)
