#!/usr/bin/guile
!#

(import (sph filesystem) (sph alist)
  (sph hashtable) (sph io)
  (sph list) (sph number)
  (sph other) (sph process) (sph string) (sph vector) (sph) (sph filesystem tag) (sph cli))

(define (tag-sort-cli)
  (let (arguments ((cli-create #:options (q (((path ...) #:required? #t))))))
    (alist-bind arguments (path) (tag-sort path))))

(tag-sort-cli)
