#!/usr/bin/guile
!#

(import (sph base) (sph filesystem tag) (sph cli))

(define (tag-sort-cli)
  (let (arguments ((cli-create #:options (list-q ((path ...) #:required? #t)))))
    (alist-bind arguments (path) (tag-sort path))))

(tag-sort-cli)
