#!/usr/bin/guile
!#

(use-modules (sph filesystem) (sph hashtable)
  (sph io) (sph list)
  (sph number) (sph other)
  (sph process) (sph string) (sph vector) (sph) (sph filesystem tag) (sph alist) (sph cli))

(define (tag-add-cli)
  (let (arguments ((cli-create #:options (q (((tags path ...) #:required? #t))))))
    (alist-bind arguments (tags path) (tag-add (string-split tags #\.) path))))

(tag-add-cli)
