#!/usr/bin/env ruby

binary_data = STDIN.read
binary_output = []

binary_data.each_byte do |byte|
  binary_string = byte.to_s(2).rjust 8, "0"
  binary_output << binary_string
end

puts binary_output.join ""
