#!/bin/sh
# reads from standard input and converts from sxml to xml
# depends on sph-lib

guile -c '(import (sph) (sxml simple) (sph read-write)) (sxml->xml (rw-port->list read (current-input-port)))'