#!/usr/bin/guile
!#

(import (sph common) (sph filesystem faceted) (sph cli))

(define (name-sort-cli)
  (let (arguments ((cli-create #:options (ql ((path ...) #:required? #t)))))
    (alist-bind arguments (path) (file-name-facets-sort path))))

(name-sort-cli)
