#!/usr/bin/guile
!#

(import (sph common) (sph filesystem faceted) (sph cli))

(define (name-add-cli)
  (let (arguments ((cli-create #:options (ql ((names path ...) #:required? #t)))))
    (alist-bind arguments (names path) (file-name-facet-add (string-split names #\.) path))))

(name-add-cli)
