#!/usr/bin/guile
!#

;displays given day kiloseconds converted to hh:mm:ss time notation
;ks2trad :: number
;example: ks2trad 53.4 -> 14:50:00
(import (sph base) (sph time utc))
(define (fill-zeros a) (string-fill-left a 2 #\0))

(let (ks (string->number (first (tail (program-arguments)))))
  (apply simple-format #t
    "~A:~A:~A\n"
    (map (compose fill-zeros number->string inexact->exact) (utc-duration->hms (* 1000 ks)))))
