#!/usr/bin/guile
!#

(import (sph) (sph number))

(define* (trad2ks hours #:optional (minutes 0) (seconds 0))
  (truncate-to-decimal-places (+ (* hours 3.6) (* minutes 0.06) (* seconds 0.001)) 2))

(let (arguments (map string->number (string-split (first (tail (program-arguments))) #\:)))
  (display-line (apply trad2ks arguments)))