#!/usr/bin/guile
!#

; converts comma separated strings into newline separated strings.
; reads from standard input
; depends on: sph-lib
(use-modules (sph stream))

(stream-each (lambda (a) (display (string-trim-both a)) (newline))
  (port->delimited-stream "," (current-input-port)))
