#!/usr/bin/guile
!#

;for each line, replace whitespace multiples with one space.
(import (sph common))
(define (string-compress-whitespace a) "string -> string" (regexp-replace a "\\s{2,}" " "))

(port-lines-each (l (e) (display (string-compress-whitespace e))) (current-input-port)
  #:handle-delim (q concat))
