#!/bin/sh

# like itpn but in --split mode and automatically writing to the files "matches" and "rejects".
# if any of the files already exists, the old file is not overwritten but a file with a unique suffix is created.
# usage example: itpn-split --search=computer

matches="$(get-unique-path matches)"
rejects="$(get-unique-path rejects)"
itpn --split --output-file-1="$matches" --output-file-2="$rejects" $@
