#!/usr/bin/guile
!#

(use-modules (sph stream))

(let* ((lines (port->line-stream (current-input-port))) (rest (stream-tail lines)))
  (display (stream-first lines)) (stream-each (lambda (a) (display ", ") (display a)) rest))
