#!/usr/bin/guile
!#
; reads from standard input
; depends on: sph-lib

(import (sph base) (sph io) (srfi srfi-41) (sph stream))

(stream-each (l (e) (display e) (display "\n"))
  (port->delimited-stream " " (current-input-port)))
